### ISSUE TITLE
정답확인 버튼 삭제 함수 추가했습니다.

### ISSUE THREAD

**Issue by khl2bb** [CodingDolharrbang/JejuQuiz#11]
https://github.com/CodingDolharrbang/JejuQuiz/commit/d261dee1f0bcc1cfddcebc4cb178a4be43a5446a
정답확인 버튼 삭제 함수 추가했습니다
다음문제 버튼 테스트중입니다.

**Comment by whe0107** [comment]
다음 문제로 넘어가는 버튼 해보는 중입니다!!

**Comment by YeSeul-0w0** [comment]
다음문제 버튼 출력이 잘 되지 않아 현재 input으로 타입을 변경하여 append시도해보고 있습니다.

**Comment by YeSeul-0w0** [comment]
다음문제 넘어가는 버튼 input button으로 append하여 master branch에 커밋하였습니다.
버튼 이벤트 발생시 다음 문제로 넘어가는 걸 해보겠습니다.

**Comment by YeSeul-0w0** [comment]
현재 버튼이 클릭되었을 때 이벤트가 발생하지 않는 다는 문제점을 발견했습니다.

**Comment by YeSeul-0w0** [comment]
다음문제 버튼을 누를시 다음 문제가 뜨게 하였습니다.
→'다음문제'라는 버튼이 클릭 될 때 function removeSubmit()함수의 removeThing.parentNode.removeChild(removeThing); 부분이 에러가 나서 한 번 확인 부탁드리겠습니다.
@khl2bb

**Comment by YeSeul-0w0** [comment]
다음문제 버튼이 나오고 나서 정답확인 버튼이 나오지 않아 그냥 '정답확인'과 '다음문제'버튼을  각각 따로 만들었습니다.
master branch로 커밋했습니다.

**Comment by YeSeul-0w0** [comment]
버튼이 너무 작아 크기를 살짝 키웠습니다.

**Comment by YeSeul-0w0** [comment]
버튼 디자인을 수정했습니다.
