### ISSUE TITLE
마스터 브랜치로 웹서빙 

### ISSUE THREAD

**Issue by niceaji** [CodingDolharrbang/JejuQuiz#17]
- index.html 웹서빙 
- 실시간 확인가능

**Comment by niceaji** [comment]
@Choi33 https://github.com/orgs/CodingDolharrbang/people 여기서 권한을 owner로 부탁드려요.

**Comment by YeSeul-0w0** [comment]
@niceaji  owner로 권한을 바꾸었습니다!

**Comment by niceaji** [comment]
https://codingdolharrbang.github.io/JejuQuiz/
이미 누군가 해놓으셨네요  @Choi33 @whe0107 @khl2bb
