### ISSUE TITLE
퀴즈 정답 확인 코드

### ISSUE THREAD

**Issue by YeSeul-0w0** [CodingDolharrbang/JejuQuiz#7]
Jquery를 이용하여 퀴즈 정답 판별

**Comment by YeSeul-0w0** [comment]
정답 확인을 눌렀을 때, value값이 hit값과 일치하는지 확인하는 checkAns 함수를 quiz.js에 추가하였습니다.
→ 해당 코드는 master branch에 push해두었습니다.

**Comment by YeSeul-0w0** [comment]
정답이 아닐 때 해설을 list형태로 html에 표현 되게 하였습니다. (master branch에 커밋)
다음 문제로 넘어갈 때 문제와 해설이 지워지지 않는 상황입니다.
다음 문제로 넘어가는 버튼을 만들어 해당 버튼 이벤트가 발동할 때 원래 있던 문제(해설이 html에 출력 되어 있다면 해설도 삭제) 삭제하고 새로운 문제를 출력하는 방식으로 가야할 것 같습니다.

**Comment by YeSeul-0w0** [comment]
hit에 빼기 1을 해주었으며, 보기가 갱신되지 않는 문제가 발생해 이를 수정해야할 것 같습니다.

**Comment by YeSeul-0w0** [comment]
보기가 갱신되지 않는 문제점을 해결했습니다.
master branch에 수정된 코드를 백업했습니다.

**Comment by Choi33** [comment]
마지막 문제가 출력되면 결과 확인 버튼이 출력되도록했습니다.
결과 확인 버튼을 눌르면 id값 team 쪽에 점수가 출력되도록했지만 버튼 클릭시 #team으로 이동하는 방법을 아직 찾지 못했습니다.
