### ISSUE TITLE
Json파일 수정

### ISSUE THREAD

**Issue by YeSeul-0w0** [CodingDolharrbang/JejuQuiz#9]
1. 정답 추가
2. 해설 추가
3. 보기 수정
4. 오타 교정
5. 문제 추가

**Comment by YeSeul-0w0** [comment]
@whe0107  : 10번까지 정답추가, 해설추가 완료

**Comment by khl2bb** [comment]
문제 20번까지 정답추가, 해설추가 완료 // updated quiz.js
#https://github.com/CodingDolharrbang/JejuQuiz/commit/aac40ec2ab79aa59a2a90c6bdd660aae512aa7e6

**Comment by khl2bb** [comment]
> 문제 20번까지 정답추가, 해설추가 완료 
+
가독성을 위해, 수정한 부분에 여백, 들여쓰기를 통일하였습니다.
https://github.com/CodingDolharrbang/JejuQuiz/commit/02ab93692828eb2019dba0ac6ee52ca79bc6d195

question에는 '도체비꽃'
해설에는 "도체비꽃"
이렇게 따옴표가 다른데 
그냥 둘까요 아니면 이런 부분들만 따옴표를 바꿀까요?

부분
{
    "question" : "제주 방언 중 '도체비꽃'은 무슨 뜻인가?",
    "examples":[
      '유체꽃',
      '수국',
      '동백',
      '벚꽃',
    ],
    hit:2,
    "ex":[
      '답은 2번이다',
      '해설 : 제주 방언 중 "도체비꽃"에 해당하는 꽃은 수국이다'
    ]
  },

**Comment by YeSeul-0w0** [comment]
@khl2bb 음 상관 없을 것 같지만 통일하면 보기 좋을 것 같네요! 
"해설 : 제주방언 중 '도체비꽃'에 해당하는 꽃은 수둑이다." 라는 식으로 써도 괜찮을 것 같습니다!!

**Comment by khl2bb** [comment]
앞에 1~10번 문제 해설과 비슷한 문맥으로 통일 시켰습니다. 따옴표를 안 쓰는 쪽으로 바꿨습니다.
https://github.com/CodingDolharrbang/JejuQuiz/commit/4e55cb417b4404f5f0d2ae236e26e3ff78f26d12

**Comment by YeSeul-0w0** [comment]
정답 판별 과정에서 hit 부분의 문제점을 발견했습니다.
우리는 1부터 시작하는게 일반적이지만 컴퓨터 기준에는 0부터 시작하는 것이 일반적입니다.
따라서 보기의 value값은 1번은 0, 2번은 1 이런식으로 할당되어 있어 hit값을 하나씩 줄여야할 것 같습니다.
▶ 정답 판별 함수에서 value값을 받고 +1을 하려했지만 value값이 문자로 넘어와 +1을 할 경우 '11' 혹은 '21' 이런 식으로 출력되는 문제가 발생했습니다.)
▶ 1번 문제만 hit값을 -1 줄인 상태입니다.

**Comment by khl2bb** [comment]
1번 문제 hit값 다시 복귀시켰습니다.
#https://github.com/CodingDolharrbang/JejuQuiz/commit/8cd33e5ec12552351a910dd1b8ab984c1153a674

문자로 넘어온 것을 number() 나 곱하기 1연산을 하면 타입 변환을 할 수 있을 것 같습니다.
